
import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "pt-BR" | "en-US" | "es-ES";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translations: Record<string, string>;
}

const translations: Record<Language, Record<string, string>> = {
  "pt-BR": {
    "basic_plan": "Básico",
    "professional_plan": "Profissional",
    "enterprise_plan": "Empresarial",
    "basic_plan_desc": "Ideal para profissionais autônomos e pequenas empresas",
    "professional_plan_desc": "Perfeito para construtoras de médio porte",
    "enterprise_plan_desc": "Para empresas de grande porte e projetos complexos",
    "per_month": "/mês",
    "up_to_5_projects": "Até 5 projetos simultâneos",
    "up_to_15_projects": "Até 15 projetos simultâneos",
    "unlimited_projects": "Projetos ilimitados",
    "two_users": "2 usuários incluídos",
    "ten_users": "10 usuários incluídos",
    "unlimited_users": "Usuários ilimitados",
    "real_time_monitoring": "Monitoramento em tempo real",
    "basic_reports": "Relatórios básicos",
    "advanced_reports": "Relatórios avançados",
    "custom_reports": "Relatórios customizados",
    "complete_budget_control": "Controle orçamentário completo",
    "mobile_app_access": "Acesso ao aplicativo móvel",
    "calendar_integration": "Integração com calendário",
    "api_integrations": "API para integrações",
    "advanced_security": "Segurança avançada",
    "daily_backup": "Backup automático diário",
    "document_management": "Gerenciamento de documentos",
    "email_support": "Suporte por email",
    "priority_support": "Suporte prioritário",
    "support_24_7": "Suporte 24/7 com atendente dedicado",
    "start_now": "Começar Agora",
    "choose_plan": "Escolher Plano",
    "talk_to_consultant": "Falar com Consultor",
    "most_popular": "Mais Popular",
    "whats_included": "O que está incluído",
    "terms_eula_agreement": "Este Contrato de Licença de Usuário Final (\"EULA\") é um acordo legal entre o usuário pessoa física ou jurídica (o \"USUÁRIO\") e a UPDATE DIGITAL TECNOLOGIA DA INFORMAÇÃO LTDA, sociedade empresária limitada, devidamente inscrita no CNPJ/MF sob o nº 21.600.669/0001-94, com sede na cidade Santa Luzia, no endereço sito à Rua Teófilo Otoni, nº 106, Quarenta e Dois, Estado de Minas Gerais, neste ato representada na forma do contrato social, doravante denominado, (a \"LICENCIANTE\") para uso de programa de computador (\"SOFTWARE\"), que incluem sistemas, sites e qualquer serviço prestado pela LICENCIANTE, pelo prazo em que utilizá-lo.",
    "terms_declaration_title": "1. DECLARAÇÃO DE VONTADE",
    "terms_declaration_desc": "1.1. O USUÁRIO declara ter lido, compreendido e aceito todos os termos e condições deste EULA, e declara, ainda, ter ciência dos direitos e obrigações nele contido, constituindo este instrumento o acordo completo entre as partes.",
    "terms_license_title": "2. LICENÇA DE USO DO SOFTWARE",
    "terms_license_desc_1": "2.1. A LICENCIANTE, que é proprietária e legítima possuidora de todos os direitos sobre o SOFTWARE, licencia, enquanto viger este EULA, ao USUÁRIO o direito de uso não exclusivo, intransferível a terceiros, sob qualquer forma ou condição. Ao utilizar o SOFTWARE, mesmo que parcial ou a título de teste, o USUÁRIO estará vinculado aos termos deste EULA, concordando com os mesmos. Em caso de discordância dos termos aqui apresentados, a utilização do SOFTWARE deve ser imediatamente interrompida.",
    "terms_license_desc_2": "2.2. Sujeito aos termos e condições do presente instrumento, este EULA concede ao USUÁRIO uma licença revogável, não exclusiva e intransferível para usar o SOFTWARE. O USUÁRIO não poderá utilizar e nem permitir o uso do SOFTWARE para outra finalidade que não seja o uso interno. Esta licença não implica na capacidade de acessar outros softwares além daqueles originalmente localizados no SOFTWARE. Em nenhuma hipótese o USUÁRIO terá acesso ao código fonte do SOFTWARE ora licenciado, por este se tratar de propriedade intelectual da LICENCIANTE.",
    "terms_license_desc_3": "2.3. A licença atribuída a este EULA restringe-se à utilização do SOFTWARE nos limites necessários para a prestação do serviço pela LICENCIANTE. O USUÁRIO não adquire, pelo presente instrumento, nenhum direito de propriedade intelectual ou outros direitos exclusivos, incluindo patentes, desenhos, marcas, direitos autorais ou direitos sobre informações confidenciais ou segredos de negócio, sobre ou relacionados ao SOFTWARE ou nenhuma parte dele. O USUÁRIO também não adquire nenhum direito sobre ou relacionado ao SOFTWARE ou qualquer componente dele, além dos direitos expressamente licenciados ao mesmo sob o presente EULA ou em qualquer outro contrato mutuamente acordado por escrito que o USUÁRIO possa ter celebrado com a LICENCIANTE. Quaisquer direitos não expressamente concedidos sob o presente instrumento são reservados.",
    "register_information": "Registre as informações",
    "register_information_desc": "Adicione fotos, vídeos, comentários e dados importantes sobre o andamento da obra",
    "share_and_follow": "Compartilhe e acompanhe",
    "share_and_follow_desc": "Compartilhe os relatórios com clientes e equipe, e acompanhe o progresso da obra",
    "who_is_for": "Para quem é o App Monitorie Suas Obras?",
    "who_is_for_desc": "Nossa plataforma é ideal para profissionais e empresas do setor da construção civil que buscam uma solução eficiente para o gerenciamento de obras:",
    "app_benefits_title": "Este aplicativo é ideal para engenheiros, gestor de obra, construtoras, fiscais de obra ou qualquer empresa de serviço que precisa de uma solução simples e fácil de utilizar para:",
    "benefit_1": "Acompanhar várias obras ao mesmo tempo",
    "benefit_2": "Registrar e ter um histórico do dia a dia da obra",
    "benefit_3": "Registrar fotos e vídeos",
    "benefit_4": "Facilitar a comunicação entre canteiro de obra e escritório",
    "benefit_5": "Fazer análise dos dados para melhor tomada de decisão",
    "benefit_6": "Saber quais os problemas e desafios estão acontecendo diariamente durante a execução da obra",
    "benefit_7": "Compartilhar as informações com o cliente da obra e demonstrar transparência dos serviços executados",
    "benefit_track_multiple_works": "Acompanhar várias obras ao mesmo tempo",
    "benefit_daily_history": "Registrar e ter um histórico do dia a dia da obra",
    "benefit_photos_videos": "Registrar fotos e vídeos",
    "benefit_communication": "Facilitar a comunicação entre canteiro de obra e escritório",
    "benefit_data_analysis": "Fazer análise dos dados para melhor tomada de decisão",
    "benefit_daily_challenges": "Saber quais os problemas e desafios estão acontecendo diariamente durante a execução da obra",
    "benefit_share_info": "Compartilhar as informações com o cliente da obra e demonstrar transparência dos serviços executados",
    "report_should_not_be_complicated": "O relatório de obra não precisa ser complicado",
    "report_should_be_simple": "Com o App Monitorie Suas Obras, você tem uma solução simples e eficiente para o gerenciamento diário das suas construções.",
    "target_audience_1": "Engenheiros e Arquitetos",
    "target_audience_1_desc": "Profissionais que precisam gerenciar múltiplos projetos simultaneamente",
    "target_audience_2": "Construtoras e Incorporadoras",
    "target_audience_2_desc": "Empresas que necessitam de controle centralizado de suas obras",
    "target_audience_3": "Gestores de Obras",
    "target_audience_3_desc": "Responsáveis pelo acompanhamento diário e tomada de decisões",
    "target_audience_4": "Fiscais e Supervisores",
    "target_audience_4_desc": "Profissionais que precisam documentar e reportar o progresso das obras",
    "what_to_register": "O que registrar no relatório?",
    "what_to_register_desc": "Tudo que você precisa para registrar o dia a dia de sua obra, e ter segurança para armazenar as informações e compartilhar de forma simples com todos os envolvidos no projeto.",
    "project_info": "Informações da obra",
    "deadlines": "Prazos",
    "work_hours": "Horário de trabalho",
    "weather_condition": "Condição climática",
    "workforce": "Mão de obra",
    "equipment": "Equipamentos",
    "completed_tasks": "Tarefas realizadas",
    "issues": "Problemas (ocorrências)",
    "received_materials": "Materiais recebidos",
    "comments": "Comentários",
    "photos_videos": "Fotos e Vídeo",
    "attachments": "Anexos",
    "how_it_works_title": "O que é o App Monitorie Suas Obras?",
    "how_it_works_description": "É um software que permite registrar e acompanhar diariamente os serviços realizados nas obras, através de um relatório padronizado \"Relatório Monitorie Suas Obras (RMO)\", fácil de preencher e simples de acompanhar.",
    "try_free": "Experimente 30 Dias Grátis",
    "daily_history": "Permite ter um histórico diário de tudo que aconteceu, saber os principais problemas e ocorrências que estão acontecendo nas obras.",
    "record_activities": "Registrar as atividades executadas, mão de obra e pessoas presentes, fotos e vídeos da execução diária.",
    "keep_client_updated": "Manter o cliente da obra atualizado diariamente sobre a evolução do projeto e facilitar a comunicação entre o canteiro de obra, fiscalização, gestor de obra, engenheiro responsável, diretor e o escritório da empresa.",
    "how_it_works_practice": "Como funciona na prática o App Monitorie Suas Obras",
    "report_value": "O relatório Monitorie Suas Obras é um sistema online valioso para o gerenciamento de obras de construção.",
    "helps_monitor": "Te ajuda a monitorar o progresso da obra, identificar problemas, melhorar a comunicação, documentar o projeto, gerenciar recursos, identificar oportunidades de melhoria e muito mais.",
    "simple_standardized": "Veja como o funcionamento é simples e padronizado",
    "register_works": "Cadastre suas obras",
    "register_works_desc": "Cadastre todas as suas obras no sistema",
    "create_daily_reports": "Crie relatórios diários",
    "create_daily_reports_desc": "Para cada dia de trabalho na obra, se cria um relatório",
    "home": "Início",
    "how_it_works": "Como Funciona",
    "features": "Funcionalidades",
    "pricing": "Planos",
    "contact": "Contato",
    "access_panel": "Acessar Painel",
    "get_started": "Comece Gratuitamente",
    "see_demo": "Ver Demonstração",
    "manage_efficiently": "Gerencie suas obras com eficiência",
    "simplify_management": "Simplifique o gerenciamento das suas",
    "civil_works": "obras civis",
    "platform_description": "Uma plataforma completa para acompanhar o progresso, gerenciar recursos e manter o controle de todas as suas construções em um só lugar.",
    "trusted_companies": "Mais de 500 empresas confiam em nossa plataforma",
    "project_progress": "Progresso do projeto",
    "know_how_it_works": "Saiba como funciona o App Monitorie Suas Obras",
    "main_features": "Funcionalidades Principais",
    "everything_you_need": "Tudo o que você precisa para gerenciar suas obras",
    "platform_tools": "Nossa plataforma reúne todas as ferramentas necessárias para que engenheiros, arquitetos e construtoras monitorem seus projetos com eficiência.",
    "our_plans": "Nossos Planos",
    "choose_ideal_plan": "Escolha o plano ideal para o seu negócio",
    "flexible_packages": "Oferecemos pacotes flexíveis que se adaptam às necessidades de profissionais e empresas de todos os portes.",
    "custom_plan": "Precisa de um plano personalizado?",
    "talk_to_team": "Fale com nossa equipe para criar um plano sob medida para sua empresa.",
    "request_proposal": "Solicitar Proposta",
    "privacy_policy": "Política de Privacidade",
    "terms_of_use": "Termos de Uso",
    "general_info": "INFORMAÇÕES GERAIS",
    "treatment_agents": "AGENTES DE TRATAMENTO",
    "controller": "Controlador",
    "data_protection_officer": "Encarregado",
    "terms_title": "Termos de Uso",
    "privacy_title": "Política de Privacidade",
    "terms_intro": "Este contrato refere-se ao sistema Monitorie Suas Obras Online.",
    "terms_eula_title": "CONTRATO DE LICENÇA PARA USUÁRIO FINAL (EULA)",
    "privacy_general_info": "1. INFORMAÇÕES GERAIS",
    "privacy_treatment_agents": "2. AGENTES DE TRATAMENTO",
    "privacy_controller": "2.1 Controlador",
    "privacy_dpo": "2.2 Encarregado",
    "terms_acceptance": "Ao acessar e utilizar o sistema Monitorie Suas Obras Online, você concorda com estes termos de uso.",
    "terms_service_description": "O sistema Monitorie Suas Obras Online é uma plataforma de gerenciamento de obras que oferece ferramentas para controle e monitoramento de projetos de construção.",
    "terms_user_obligations": "Obrigações do Usuário",
    "terms_user_obligations_desc": "O usuário se compromete a utilizar o sistema de forma ética e legal, respeitando todas as leis e regulamentos aplicáveis.",
    "terms_confidentiality": "Confidencialidade",
    "terms_confidentiality_desc": "Todas as informações fornecidas pelo usuário são tratadas com confidencialidade, conforme nossa Política de Privacidade.",
    "terms_intellectual_property": "Propriedade Intelectual",
    "terms_intellectual_property_desc": "Todo o conteúdo e software do sistema são protegidos por direitos autorais e outras leis de propriedade intelectual.",
    "terms_liability": "Limitação de Responsabilidade",
    "terms_liability_desc": "O sistema é fornecido 'como está', sem garantias de qualquer tipo, expressas ou implícitas.",
    "terms_modifications": "Modificações dos Termos",
    "terms_modifications_desc": "Reservamos o direito de modificar estes termos a qualquer momento, notificando os usuários sobre alterações significativas.",
    "terms_termination": "Encerramento",
    "terms_termination_desc": "Podemos encerrar ou suspender o acesso ao sistema em caso de violação destes termos.",
    "terms_applicable_law": "Lei Aplicável",
    "terms_applicable_law_desc": "Estes termos são regidos pelas leis do Brasil.",
    "terms_duration_title": "3. DO PRAZO E RESCISÃO",
    "terms_duration_1": "3.1. O presente EULA entra em vigor na data de seu aceite pelo USUÁRIO;",
    "terms_duration_2": "3.2. O prazo de licenciamento vigorará pelo prazo indeterminado, porém poderá ser rescindido a qualquer tempo, por qualquer das partes, desde que denunciado com 7 (sete) dias de antecedência;",
    "terms_duration_3": "3.3. A rescisão não trará ônus para qualquer uma das partes;",
    "terms_duration_4": "3.4. Em caso de rescisão por parte do USUÁRIO, a solicitação precisa ser feita pelo e-mail oficial da LICENCIANTE, conforme o item 5.3, solicitando o cancelamento do serviço;",
    "terms_duration_5": "3.5. Quando a rescisão deste EULA for solicitada pelo USUÁRIO, será concedido ao USUÁRIO um prazo de até 7 (sete) dias, destinados as providências de encerramento;",
    "terms_duration_6": "3.6. A rescisão deste EULA estará condicionada à liquidação de todos os valores devidos até o dia da rescisão;",
    "terms_duration_7": "3.7. No período do aviso prévio para o cancelamento do contrato o USUÁRIO poderá realizar o backup dos relatórios em formato PDF, o SOFTWARE disponibiliza um recurso para que o USUÁRIO possa baixar múltiplos relatórios por obra, acessando pela versão WEB. Após este prazo os dados poderão ser permanentemente excluídos.",
    "terms_payment_title": "4. DA REMUNERAÇÃO",
    "terms_payment_1": "4.1. O USUÁRIO pagará de forma antecipada à LICENCIANTE os valores especificados no plano escolhido no ato da contratação;",
    "terms_payment_2": "4.2. Caso o USUÁRIO, no decorrer da vigência do presente instrumento, deseje mudar de plano, deverá pagar os valores de acordo com o novo plano e, caso haja taxa de adesão, pagar a diferença entre a adesão previamente paga e a adesão para o novo plano, em até duas parcelas iguais e consecutivas;",
    "terms_payment_3": "4.3. Não será devolvida a taxa de adesão, caso a mudança seja para um plano de menor valor;",
    "terms_payment_4": "4.4. Caso o USUÁRIO, no decorrer da vigência do presente instrumento, deseje cancelar sua adesão, nenhum valor já pago será reembolsado ou devolvido. O acesso ao SOFTWARE será mantido até o final do prazo contratado, não sendo renovada sua assinatura no próximo ciclo de cobrança (mensal ou anual).",
    "terms_payment_5": "4.5. AS PARTES poderão mudar automaticamente o plano escolhido inicialmente para um plano superior, caso os limites estipulados anteriormente sejam atingidos;",
    "terms_payment_6": "4.6. Pagamentos efetuados após o vencimento terão o valor principal acrescido de correção monetária, juros de mora de 1% (um por cento) ao mês, multa de 2% (dois por cento), honorários advocatícios e custas processuais, caso haja necessidade de intervenção de advogado para a cobrança da dívida, tudo sem prejuízo das medidas contratuais e legais cabíveis;",
    "terms_payment_7": "4.7. A falta de pagamento na data determinada para seu vencimento acarretará a suspensão de acesso ao SOFTWARE até que a pendência financeira seja regularizada;",
    "terms_payment_8": "4.8. Caso a suspensão, cancelamento ou fim do teste permaneça por prazo superior a 90 (noventa) dias, o USUÁRIO concorda que o LICENCIANTE poderá excluir integralmente as informações lançadas no SOFTWARE pelo USUÁRIO.",
    "terms_user_obligations_title": "5. DAS OBRIGAÇÕES DO USUÁRIO",
    "terms_user_obligations_intro": "Obriga-se o USUÁRIO a:",
    "terms_user_obligations_1": "5.1. Manter, a seus dispêndios, acesso a Internet banda larga para utilizar o SOFTWARE;",
    "terms_user_obligations_2": "5.2. Acessar o SOFTWARE via browser recomendado pelo LICENCIANTE e mantê-lo sempre atualizado na última versão do fabricante;",
    "terms_user_obligations_3": "5.3. Comunicar-se oficialmente com a LICENCIANTE pelo email suporte@monitoriesuasobras.net;",
    "terms_user_obligations_4": "5.4. Manter, a seus dispêndios, um endereço de email, válido e frequentemente lido, nos cadastros da LICENCIANTE para que ela possa se comunicar de forma oficial;",
    "terms_user_obligations_5": "5.5. Pagar os valores referentes à licença na forma e prazos estipulados para o plano contratado;",
    "social_facebook": "Siga-nos no Facebook",
    "social_instagram": "Siga-nos no Instagram",
    "social_twitter": "Siga-nos no Twitter",
    "social_linkedin": "Siga-nos no LinkedIn"
  },
  "en-US": {
    "basic_plan": "Basic",
    "professional_plan": "Professional",
    "enterprise_plan": "Enterprise",
    "basic_plan_desc": "Ideal for freelancers and small businesses",
    "professional_plan_desc": "Perfect for medium-sized construction companies",
    "enterprise_plan_desc": "For large companies and complex projects",
    "per_month": "/month",
    "up_to_5_projects": "Up to 5 simultaneous projects",
    "up_to_15_projects": "Up to 15 simultaneous projects",
    "unlimited_projects": "Unlimited projects",
    "two_users": "2 users included",
    "ten_users": "10 users included",
    "unlimited_users": "Unlimited users",
    "real_time_monitoring": "Real-time monitoring",
    "basic_reports": "Basic reports",
    "advanced_reports": "Advanced reports",
    "custom_reports": "Custom reports",
    "complete_budget_control": "Complete budget control",
    "mobile_app_access": "Mobile app access",
    "calendar_integration": "Calendar integration",
    "api_integrations": "API for integrations",
    "advanced_security": "Advanced security",
    "daily_backup": "Daily automatic backup",
    "document_management": "Document management",
    "email_support": "Email support",
    "priority_support": "Priority support",
    "support_24_7": "24/7 support with dedicated agent",
    "start_now": "Start Now",
    "choose_plan": "Choose Plan",
    "talk_to_consultant": "Talk to Consultant",
    "most_popular": "Most Popular",
    "whats_included": "What's included",
    "terms_eula_agreement": "This End User License Agreement (\"EULA\") is a legal agreement between the individual or legal entity user (the \"USER\") and UPDATE DIGITAL TECNOLOGIA DA INFORMAÇÃO LTDA, a limited liability company, duly registered under CNPJ/MF No. 21.600.669/0001-94, headquartered in Santa Luzia city, at Rua Teófilo Otoni, No. 106, Quarenta e Dois, State of Minas Gerais, herein represented in accordance with its bylaws, hereinafter referred to as (the \"LICENSOR\") for the use of computer program (\"SOFTWARE\"), which includes systems, websites and any service provided by the LICENSOR, for the period of its use.",
    "terms_declaration_title": "1. DECLARATION OF WILL",
    "terms_declaration_desc": "1.1. The USER declares to have read, understood and accepted all terms and conditions of this EULA, and further declares to be aware of the rights and obligations contained therein, this instrument constituting the complete agreement between the parties.",
    "terms_license_title": "2. SOFTWARE LICENSE",
    "terms_license_desc_1": "2.1. The LICENSOR, which is the owner and legitimate holder of all rights to the SOFTWARE, licenses, while this EULA is in effect, to the USER the non-exclusive right of use, non-transferable to third parties, under any form or condition. By using the SOFTWARE, even partially or for testing purposes, the USER will be bound by the terms of this EULA, agreeing to them. In case of disagreement with the terms presented herein, the use of the SOFTWARE must be immediately discontinued.",
    "terms_license_desc_2": "2.2. Subject to the terms and conditions of this instrument, this EULA grants the USER a revocable, non-exclusive and non-transferable license to use the SOFTWARE. The USER may not use or allow the use of the SOFTWARE for any purpose other than internal use. This license does not imply the ability to access software other than those originally located in the SOFTWARE. Under no circumstances will the USER have access to the source code of the licensed SOFTWARE, as this is intellectual property of the LICENSOR.",
    "terms_license_desc_3": "2.3. The license attributed to this EULA is restricted to the use of the SOFTWARE within the limits necessary for the provision of service by the LICENSOR. The USER does not acquire, through this instrument, any intellectual property rights or other exclusive rights, including patents, designs, trademarks, copyrights or rights over confidential information or trade secrets, about or related to the SOFTWARE or any part thereof. The USER also does not acquire any rights over or related to the SOFTWARE or any component thereof, beyond the rights expressly licensed to it under this EULA or any other mutually agreed written contract that the USER may have entered into with the LICENSOR. Any rights not expressly granted under this instrument are reserved.",
    "who_is_for": "Who is the Monitor Your Construction App for?",
    "who_is_for_desc": "Our platform is ideal for professionals and companies in the civil construction sector who are looking for an efficient solution for construction management:",
    "app_benefits_title": "This app is ideal for engineers, construction managers, construction companies, site inspectors, or any service company that needs a simple and easy-to-use solution to:",
    "benefit_1": "Monitor multiple construction sites simultaneously",
    "benefit_2": "Record and maintain a daily history of the construction site",
    "benefit_3": "Record photos and videos",
    "benefit_4": "Facilitate communication between construction site and office",
    "benefit_5": "Analyze data for better decision making",
    "benefit_6": "Know what problems and challenges are happening daily during construction",
    "benefit_7": "Share information with the construction client and demonstrate transparency of services performed",
    "benefit_track_multiple_works": "Monitor multiple construction sites simultaneously",
    "benefit_daily_history": "Record and maintain a daily history of the construction site",
    "benefit_photos_videos": "Record photos and videos",
    "benefit_communication": "Facilitate communication between construction site and office",
    "benefit_data_analysis": "Analyze data for better decision making",
    "benefit_daily_challenges": "Know what problems and challenges are happening daily during construction",
    "benefit_share_info": "Share information with the construction client and demonstrate transparency of services performed",
    "report_should_not_be_complicated": "Construction reporting doesn't have to be complicated",
    "report_should_be_simple": "With the Monitor Your Construction App, you have a simple and efficient solution for the daily management of your construction projects.",
    "target_audience_1": "Engineers and Architects",
    "target_audience_1_desc": "Professionals who need to manage multiple projects simultaneously",
    "target_audience_2": "Construction Companies and Developers",
    "target_audience_2_desc": "Companies that need centralized control of their construction projects",
    "target_audience_3": "Construction Managers",
    "target_audience_3_desc": "Those responsible for daily monitoring and decision making",
    "target_audience_4": "Inspectors and Supervisors",
    "target_audience_4_desc": "Professionals who need to document and report construction progress",
    "what_to_register": "What to register in the report?",
    "what_to_register_desc": "Everything you need to record the day-to-day of your construction site, and have security to store information and share it simply with everyone involved in the project.",
    "project_info": "Project information",
    "deadlines": "Deadlines",
    "work_hours": "Work hours",
    "weather_condition": "Weather condition",
    "workforce": "Workforce",
    "equipment": "Equipment",
    "completed_tasks": "Completed tasks",
    "issues": "Issues (occurrences)",
    "received_materials": "Received materials",
    "comments": "Comments",
    "photos_videos": "Photos and Video",
    "attachments": "Attachments",
    "how_it_works_title": "What is the Monitor Your Construction App?",
    "how_it_works_description": "It's a software that allows you to record and monitor daily services performed on construction sites, through a standardized \"Monitor Your Construction Report (MCR)\", easy to fill out and simple to follow.",
    "try_free": "Try 30 Days Free",
    "daily_history": "Allows you to have a daily history of everything that happened, know the main problems and occurrences that are happening on construction sites.",
    "record_activities": "Record the activities performed, labor and people present, photos and videos of daily execution.",
    "keep_client_updated": "Keep the client updated daily on the progress of the project and facilitate communication between the construction site, inspection, construction manager, responsible engineer, director and the company office.",
    "how_it_works_practice": "How the Monitor Your Construction App works in practice",
    "report_value": "The Monitor Your Construction Report is a valuable online system for construction project management.",
    "helps_monitor": "It helps you monitor construction progress, identify problems, improve communication, document the project, manage resources, identify improvement opportunities and much more.",
    "simple_standardized": "See how the operation is simple and standardized",
    "register_works": "Register your construction projects",
    "register_works_desc": "Register all your construction projects in the system",
    "create_daily_reports": "Create daily reports",
    "create_daily_reports_desc": "For each workday on site, a report is created",
    "home": "Home",
    "how_it_works": "How It Works",
    "features": "Features",
    "pricing": "Pricing",
    "contact": "Contact",
    "access_panel": "Access Dashboard",
    "get_started": "Get Started for Free",
    "see_demo": "See Demo",
    "manage_efficiently": "Manage your construction projects efficiently",
    "simplify_management": "Simplify the management of your",
    "civil_works": "construction projects",
    "platform_description": "A complete platform to track progress, manage resources, and maintain control of all your construction projects in one place.",
    "trusted_companies": "More than 500 companies trust our platform",
    "project_progress": "Project progress",
    "know_how_it_works": "Learn how the Monitor Your Construction App works",
    "main_features": "Main Features",
    "everything_you_need": "Everything you need to manage your construction projects",
    "platform_tools": "Our platform brings together all the necessary tools for engineers, architects, and construction companies to efficiently monitor their projects.",
    "our_plans": "Our Plans",
    "choose_ideal_plan": "Choose the ideal plan for your business",
    "flexible_packages": "We offer flexible packages that adapt to the needs of professionals and companies of all sizes.",
    "custom_plan": "Need a custom plan?",
    "talk_to_team": "Talk to our team to create a tailored plan for your company.",
    "request_proposal": "Request Proposal",
    "privacy_policy": "Privacy Policy",
    "terms_of_use": "Terms of Use",
    "general_info": "GENERAL INFORMATION",
    "treatment_agents": "TREATMENT AGENTS",
    "controller": "Controller",
    "data_protection_officer": "Data Protection Officer",
    "terms_title": "Terms of Use",
    "privacy_title": "Privacy Policy",
    "terms_intro": "This contract refers to the Monitor Your Construction Online system.",
    "terms_eula_title": "END USER LICENSE AGREEMENT (EULA)",
    "privacy_general_info": "1. GENERAL INFORMATION",
    "privacy_treatment_agents": "2. TREATMENT AGENTS",
    "privacy_controller": "2.1 Controller",
    "privacy_dpo": "2.2 Data Protection Officer",
    "terms_acceptance": "By accessing and using the Monitor Your Construction Online system, you agree to these terms of use.",
    "terms_service_description": "The Monitor Your Construction Online system is a construction management platform that offers tools for controlling and monitoring construction projects.",
    "terms_user_obligations": "User Obligations",
    "terms_user_obligations_desc": "The user agrees to use the system in an ethical and legal manner, respecting all applicable laws and regulations.",
    "terms_confidentiality": "Confidentiality",
    "terms_confidentiality_desc": "All information provided by the user is treated with confidentiality, as per our Privacy Policy.",
    "terms_intellectual_property": "Intellectual Property",
    "terms_intellectual_property_desc": "All content and software of the system are protected by copyright and other intellectual property laws.",
    "terms_liability": "Limitation of Liability",
    "terms_liability_desc": "The system is provided 'as is', without warranties of any kind, express or implied.",
    "terms_modifications": "Modifications of Terms",
    "terms_modifications_desc": "We reserve the right to modify these terms at any time, notifying users of significant changes.",
    "terms_termination": "Termination",
    "terms_termination_desc": "We may terminate or suspend access to the system in case of violation of these terms.",
    "terms_applicable_law": "Applicable Law",
    "terms_applicable_law_desc": "These terms are governed by the laws of Brazil.",
    "terms_duration_title": "3. TERM AND TERMINATION",
    "terms_duration_1": "3.1. This EULA becomes effective on the date of its acceptance by the USER;",
    "terms_duration_2": "3.2. The licensing term will be valid for an indefinite period, but may be terminated at any time by either party, provided that it is reported with 7 (seven) days notice;",
    "terms_duration_3": "3.3. The termination will not incur any costs for either party;",
    "terms_duration_4": "3.4. In case of termination by the USER, the request must be made through the LICENSOR's official email, as per item 5.3, requesting the service cancellation;",
    "terms_duration_5": "3.5. When the termination of this EULA is requested by the USER, the USER will be granted a period of up to 7 (seven) days for termination procedures;",
    "terms_duration_6": "3.6. The termination of this EULA will be conditioned to the settlement of all amounts due until the termination date;",
    "terms_duration_7": "3.7. During the notice period for contract cancellation, the USER may backup reports in PDF format, the SOFTWARE provides a feature for the USER to download multiple reports per project, accessing through the WEB version. After this period, the data may be permanently deleted.",
    "terms_payment_title": "4. REMUNERATION",
    "terms_payment_1": "4.1. The USER will pay in advance to the LICENSOR the amounts specified in the plan chosen at the time of contracting;",
    "terms_payment_2": "4.2. If the USER, during the term of this instrument, wishes to change plans, they must pay the amounts according to the new plan and, if there is a subscription fee, pay the difference between the previously paid subscription and the subscription for the new plan, in up to two equal and consecutive installments;",
    "terms_payment_3": "4.3. The subscription fee will not be refunded if the change is to a lower-value plan;",
    "terms_payment_4": "4.4. If the USER, during the term of this instrument, wishes to cancel their subscription, no amount already paid will be refunded or returned. Access to the SOFTWARE will be maintained until the end of the contracted period, and the subscription will not be renewed in the next billing cycle (monthly or annual).",
    "terms_payment_5": "4.5. THE PARTIES may automatically change the initially chosen plan to a higher plan if the previously stipulated limits are reached;",
    "terms_payment_6": "4.6. Payments made after the due date will have the principal amount plus monetary correction, late payment interest of 1% (one percent) per month, a fine of 2% (two percent), attorney's fees and court costs, if there is a need for attorney intervention for debt collection, all without prejudice to applicable contractual and legal measures;",
    "terms_payment_7": "4.7. Failure to pay on the determined due date will result in suspension of access to the SOFTWARE until the financial pending is regularized;",
    "terms_payment_8": "4.8. If the suspension, cancellation, or end of the trial remains for a period longer than 90 (ninety) days, the USER agrees that the LICENSOR may completely delete the information entered in the SOFTWARE by the USER.",
    "terms_user_obligations_title": "5. USER OBLIGATIONS",
    "terms_user_obligations_intro": "The USER is obligated to:",
    "terms_user_obligations_1": "5.1. Maintain, at their expense, broadband Internet access to use the SOFTWARE;",
    "terms_user_obligations_2": "5.2. Access the SOFTWARE via browser recommended by the LICENSOR and keep it always updated to the manufacturer's latest version;",
    "terms_user_obligations_3": "5.3. Communicate officially with the LICENSOR through the email support@monitoriesuasobras.net;",
    "terms_user_obligations_4": "5.4. Maintain, at their expense, a valid and frequently read email address in the LICENSOR's records so that they can communicate officially;",
    "terms_user_obligations_5": "5.5. Pay the license fees in the form and deadlines stipulated for the contracted plan;",
    "social_facebook": "Síguenos en Facebook",
    "social_instagram": "Síguenos en Instagram",
    "social_twitter": "Síguenos en Twitter",
    "social_linkedin": "Síguenos en LinkedIn",
    "social_facebook": "Follow us on Facebook",
    "social_instagram": "Follow us on Instagram",
    "social_twitter": "Follow us on Twitter",
    "social_linkedin": "Follow us on LinkedIn"
  },
  "es-ES": {
    "basic_plan": "Básico",
    "professional_plan": "Profesional",
    "enterprise_plan": "Empresarial",
    "basic_plan_desc": "Ideal para profesionales autónomos y pequeñas empresas",
    "professional_plan_desc": "Perfecto para constructoras de tamaño medio",
    "enterprise_plan_desc": "Para empresas grandes y proyectos complejos",
    "per_month": "/mes",
    "up_to_5_projects": "Hasta 5 proyectos simultáneos",
    "up_to_15_projects": "Hasta 15 proyectos simultáneos",
    "unlimited_projects": "Proyectos ilimitados",
    "two_users": "2 usuarios incluidos",
    "ten_users": "10 usuarios incluidos",
    "unlimited_users": "Usuarios ilimitados",
    "real_time_monitoring": "Monitoreo en tiempo real",
    "basic_reports": "Informes básicos",
    "advanced_reports": "Informes avanzados",
    "custom_reports": "Informes personalizados",
    "complete_budget_control": "Control presupuestario completo",
    "mobile_app_access": "Acceso a la aplicación móvil",
    "calendar_integration": "Integración con calendario",
    "api_integrations": "API para integraciones",
    "advanced_security": "Seguridad avanzada",
    "daily_backup": "Copia de seguridad automática diaria",
    "document_management": "Gestión de documentos",
    "email_support": "Soporte por email",
    "priority_support": "Soporte prioritario",
    "support_24_7": "Soporte 24/7 con agente dedicado",
    "start_now": "Comenzar Ahora",
    "choose_plan": "Elegir Plan",
    "talk_to_consultant": "Hablar con Consultor",
    "most_popular": "Más Popular",
    "whats_included": "Qué está incluido",
    "terms_eula_agreement": "Este Contrato de Licencia de Usuario Final (\"EULA\") es un acuerdo legal entre el usuario persona física o jurídica (el \"USUARIO\") y UPDATE DIGITAL TECNOLOGIA DA INFORMAÇÃO LTDA, sociedad empresarial limitada, debidamente inscrita en el CNPJ/MF bajo el nº 21.600.669/0001-94, con sede en la ciudad de Santa Luzia, en la dirección Rua Teófilo Otoni, nº 106, Quarenta e Dois, Estado de Minas Gerais, en este acto representada en la forma del contrato social, en adelante denominada (la \"LICENCIANTE\") para el uso del programa de computador (\"SOFTWARE\"), que incluye sistemas, sitios web y cualquier servicio prestado por la LICENCIANTE, por el plazo en que lo utilice.",
    "terms_declaration_title": "1. DECLARACIÓN DE VOLUNTAD",
    "terms_declaration_desc": "1.1. El USUARIO declara haber leído, comprendido y aceptado todos los términos y condiciones de este EULA, y declara, además, tener conocimiento de los derechos y obligaciones contenidos en él, constituyendo este instrumento el acuerdo completo entre las partes.",
    "terms_license_title": "2. LICENCIA DE USO DEL SOFTWARE",
    "terms_license_desc_1": "2.1. La LICENCIANTE, que es propietaria y legítima poseedora de todos los derechos sobre el SOFTWARE, licencia, mientras esté vigente este EULA, al USUARIO el derecho de uso no exclusivo, intransferible a terceros, bajo cualquier forma o condición. Al utilizar el SOFTWARE, incluso parcialmente o a título de prueba, el USUARIO estará vinculado a los términos de este EULA, concordando con los mismos. En caso de discordancia de los términos aquí presentados, la utilización del SOFTWARE debe ser inmediatamente interrumpida.",
    "terms_license_desc_2": "2.2. Sujeto a los términos y condiciones del presente instrumento, este EULA concede al USUARIO una licencia revocable, no exclusiva e intransferible para usar el SOFTWARE. El USUARIO no podrá utilizar ni permitir el uso del SOFTWARE para otra finalidad que no sea el uso interno. Esta licencia no implica la capacidad de acceder a otros softwares además de aquellos originalmente localizados en el SOFTWARE. En ninguna hipótesis el USUARIO tendrá acceso al código fuente del SOFTWARE aquí licenciado, por tratarse de propiedad intelectual de la LICENCIANTE.",
    "terms_license_desc_3": "2.3. La licencia atribuida a este EULA se restringe a la utilización del SOFTWARE en los límites necesarios para la prestación del servicio por la LICENCIANTE. El USUARIO no adquiere, por el presente instrumento, ningún derecho de propiedad intelectual u otros derechos exclusivos, incluyendo patentes, diseños, marcas, derechos de autor o derechos sobre informaciones confidenciales o secretos de negocio, sobre o relacionados al SOFTWARE o ninguna parte de él. El USUARIO tampoco adquiere ningún derecho sobre o relacionado al SOFTWARE o cualquier componente de él, además de los derechos expresamente licenciados al mismo bajo el presente EULA o en cualquier otro contrato mutuamente acordado por escrito que el USUARIO pueda haber celebrado con la LICENCIANTE. Cualesquiera derechos no expresamente concedidos bajo el presente instrumento son reservados.",
    "who_is_for": "¿Para quién es la App Monitorie Sus Obras?",
    "who_is_for_desc": "Nuestra plataforma es ideal para profesionales y empresas del sector de la construcción civil que buscan una solución eficiente para la gestión de obras:",
    "app_benefits_title": "Esta aplicación es ideal para ingenieros, gerentes de obra, constructoras, inspectores de obra o cualquier empresa de servicios que necesite una solución simple y fácil de usar para:",
    "benefit_1": "Monitorear varias obras al mismo tiempo",
    "benefit_2": "Registrar y tener un historial del día a día de la obra",
    "benefit_3": "Registrar fotos y videos",
    "benefit_4": "Facilitar la comunicación entre la obra y la oficina",
    "benefit_5": "Realizar análisis de datos para una mejor toma de decisiones",
    "benefit_6": "Saber qué problemas y desafíos están ocurriendo diariamente durante la ejecución de la obra",
    "benefit_7": "Compartir información con el cliente de la obra y demostrar transparencia en los servicios ejecutados",
    "benefit_track_multiple_works": "Monitorear varias obras al mismo tiempo",
    "benefit_daily_history": "Registrar y tener un historial del día a día de la obra",
    "register_information": "Registre as informações",
    "register_information_desc": "Adicione fotos, vídeos, comentários e dados importantes sobre o andamento da obra",
    "share_and_follow": "Compartilhe e acompanhe",
    "share_and_follow_desc": "Compartilhe os relatórios com clientes e equipe, e acompanhe o progresso da obra",
    "who_is_for": "Para quem é o App Monitorie Suas Obras?",
    "who_is_for_desc": "Nossa plataforma é ideal para profissionais e empresas do setor da construção civil que buscam uma solução eficiente para o gerenciamento de obras:",
    "app_benefits_title": "Este aplicativo é ideal para engenheiros, gestor de obra, construtoras, fiscais de obra ou qualquer empresa de serviço que precisa de uma solução simples e fácil de utilizar para:",
    "benefit_1": "Acompanhar várias obras ao mesmo tempo",
    "benefit_2": "Registrar e ter um histórico do dia a dia da obra",
    "benefit_3": "Registrar fotos e vídeos",
    "benefit_4": "Facilitar a comunicação entre canteiro de obra e escritório",
    "benefit_5": "Fazer análise dos dados para melhor tomada de decisão",
    "benefit_6": "Saber quais os problemas e desafios estão acontecendo diariamente durante a execução da obra",
    "benefit_7": "Compartilhar as informações com o cliente da obra e demonstrar transparência dos serviços executados",
    "benefit_track_multiple_works": "Acompanhar várias obras ao mesmo tempo",
    "benefit_daily_history": "Registrar e ter um histórico do dia a dia da obra",
    "benefit_photos_videos": "Registrar fotos e vídeos",
    "benefit_communication": "Facilitar a comunicação entre canteiro de obra e escritório",
    "benefit_data_analysis": "Fazer análise dos dados para melhor tomada de decisão",
    "benefit_daily_challenges": "Saber quais os problemas e desafios estão acontecendo diariamente durante a execução da obra",
    "benefit_share_info": "Compartilhar as informações com o cliente da obra e demonstrar transparência dos serviços executados",
    "report_should_not_be_complicated": "O relatório de obra não precisa ser complicado",
    "report_should_be_simple": "Com o App Monitorie Suas Obras, tienes una solución simple y eficiente para la gestión diaria de tus construcciones.",
    "target_audience_1": "Ingenieros y Arquitectos",
    "target_audience_1_desc": "Profesionales que necesitan gestionar múltiples proyectos simultáneamente",
    "target_audience_2": "Constructoras y Desarrolladoras",
    "target_audience_2_desc": "Empresas que necesitan un control centralizado de sus obras",
    "target_audience_3": "Gestores de Obras",
    "target_audience_3_desc": "Responsables del seguimiento diario y la toma de decisiones",
    "target_audience_4": "Inspectores y Supervisores",
    "target_audience_4_desc": "Profesionales que necesitan documentar y reportar el progreso de las obras",
    "what_to_register": "¿Qué registrar en el informe?",
    "what_to_register_desc": "Todo lo que necesitas para registrar el día a día de tu obra, y tener seguridad para almacenar la información y compartirla de manera simple con todos los involucrados en el proyecto.",
    "project_info": "Información del proyecto",
    "deadlines": "Plazos",
    "work_hours": "Horario de trabajo",
    "weather_condition": "Condición climática",
    "workforce": "Mano de obra",
    "equipment": "Equipos",
    "completed_tasks": "Tareas completadas",
    "issues": "Problemas (ocurrencias)",
    "received_materials": "Materiales recibidos",
    "comments": "Comentarios",
    "photos_videos": "Fotos y Video",
    "attachments": "Adjuntos",
    "how_it_works_title": "¿Qué es la App Monitorie Sus Obras?",
    "how_it_works_description": "Es un software que permite registrar y monitorear diariamente los servicios realizados en las obras, a través de un informe estandarizado \"Informe Monitorie Sus Obras (IMO)\", fácil de completar y simple de seguir.",
    "try_free": "Prueba 30 Días Gratis",
    "daily_history": "Permite tener un historial diario de todo lo que sucedió, conocer los principales problemas y ocurrencias que están sucediendo en las obras.",
    "record_activities": "Registrar las actividades ejecutadas, mano de obra y personas presentes, fotos y videos de la ejecución diaria.",
    "keep_client_updated": "Mantener al cliente de la obra actualizado diariamente sobre la evolución del proyecto y facilitar la comunicación entre la obra, fiscalización, gestor de obra, ingeniero responsable, director y la oficina de la empresa.",
    "how_it_works_practice": "Cómo funciona en la práctica la App Monitorie Sus Obras",
    "report_value": "El informe Monitorie Sus Obras es un sistema en línea valioso para la gestión de obras de construcción.",
    "helps_monitor": "Te ayuda a monitorear el progreso de la obra, identificar problemas, mejorar la comunicación, documentar el proyecto, gestionar recursos, identificar oportunidades de mejora y mucho más.",
    "simple_standardized": "Vea cómo el funcionamiento es simple y estandarizado",
    "register_works": "Registre sus obras",
    "register_works_desc": "Registre todas sus obras en el sistema",
    "create_daily_reports": "Cree informes diarios",
    "create_daily_reports_desc": "Para cada día de trabajo en la obra, se crea un informe",
    "home": "Inicio",
    "how_it_works": "Cómo Funciona",
    "features": "Características",
    "pricing": "Planes",
    "contact": "Contacto",
    "access_panel": "Acceder al Panel",
    "get_started": "Comienza Gratis",
    "see_demo": "Ver Demostración",
    "manage_efficiently": "Gestiona tus obras con eficiencia",
    "simplify_management": "Simplifica la gestión de tus",
    "civil_works": "obras civiles",
    "platform_description": "Una plataforma completa para seguir el progreso, gestionar recursos y mantener el control de todas tus construcciones en un solo lugar.",
    "trusted_companies": "Más de 500 empresas confían en nuestra plataforma",
    "project_progress": "Progreso del proyecto",
    "know_how_it_works": "Descubre cómo funciona la App Monitorie Sus Obras",
    "main_features": "Características Principales",
    "everything_you_need": "Todo lo que necesitas para gestionar tus obras",
    "platform_tools": "Nuestra plataforma reúne todas las herramientas necesarias para que ingenieros, arquitectos y constructoras monitoreen sus proyectos con eficiencia.",
    "our_plans": "Nuestros Planes",
    "choose_ideal_plan": "Elige el plan ideal para tu negocio",
    "flexible_packages": "Ofrecemos paquetes flexibles que se adaptan a las necesidades de profesionales y empresas de todos los tamaños.",
    "custom_plan": "¿Necesitas un plan personalizado?",
    "talk_to_team": "Habla con nuestro equipo para crear un plan a medida para tu empresa.",
    "request_proposal": "Solicitar Propuesta",
    "privacy_policy": "Política de Privacidad",
    "terms_of_use": "Términos de Uso",
    "general_info": "INFORMACIÓN GENERAL",
    "treatment_agents": "AGENTES DE TRATAMIENTO",
    "controller": "Controlador",
    "data_protection_officer": "Encargado de Protección de Datos",
    "terms_title": "Términos de Uso",
    "privacy_title": "Política de Privacidad",
    "terms_intro": "Este contrato se refiere al sistema Monitorie Sus Obras Online.",
    "terms_eula_title": "CONTRATO DE LICENCIA PARA USUARIO FINAL (EULA)",
    "privacy_general_info": "1. INFORMACIÓN GENERAL",
    "privacy_treatment_agents": "2. AGENTES DE TRATAMIENTO",
    "privacy_controller": "2.1 Controlador",
    "privacy_dpo": "2.2 Encargado de Protección de Datos",
    "terms_acceptance": "Al acceder y utilizar el sistema Monitorie Sus Obras Online, usted acepta estos términos de uso.",
    "terms_service_description": "El sistema Monitorie Sus Obras Online es una plataforma de gestión de obras que ofrece herramientas para el control y monitoreo de proyectos de construcción.",
    "terms_user_obligations": "Obligaciones del Usuario",
    "terms_user_obligations_desc": "El usuario se compromete a utilizar el sistema de forma ética y legal, respetando todas las leyes y regulaciones aplicables.",
    "terms_confidentiality": "Confidencialidad",
    "terms_confidentiality_desc": "Toda la información proporcionada por el usuario es tratada con confidencialidad, según nuestra Política de Privacidad.",
    "terms_intellectual_property": "Propiedad Intelectual",
    "terms_intellectual_property_desc": "Todo el contenido y software del sistema están protegidos por derechos de autor y otras leyes de propiedad intelectual.",
    "terms_liability": "Limitación de Responsabilidad",
    "terms_liability_desc": "El sistema se proporciona 'tal cual', sin garantías de ningún tipo, expresas o implícitas.",
    "terms_modifications": "Modificaciones de los Términos",
    "terms_modifications_desc": "Nos reservamos el derecho de modificar estos términos en cualquier momento, notificando a los usuarios sobre cambios significativos.",
    "terms_termination": "Terminación",
    "terms_termination_desc": "Podemos terminar o suspender el acceso al sistema en caso de violación de estos términos.",
    "terms_applicable_law": "Ley Aplicable",
    "terms_applicable_law_desc": "Estos términos se rigen por las leyes de Brasil.",
    "terms_duration_title": "3. PLAZO Y TERMINACIÓN",
    "terms_duration_1": "3.1. Este EULA entra en vigor en la fecha de su aceptación por el USUARIO;",
    "terms_duration_2": "3.2. El plazo de licencia estará vigente por un período indefinido, pero podrá ser rescindido en cualquier momento por cualquiera de las partes, siempre que se notifique con 7 (siete) días de anticipación;",
    "terms_duration_3": "3.3. La rescisión no incurrirá en costos para ninguna de las partes;",
    "terms_duration_4": "3.4. En caso de rescisión por parte del USUARIO, la solicitud debe realizarse a través del correo electrónico oficial del LICENCIANTE, según el punto 5.3, solicitando la cancelación del servicio;",
    "terms_duration_5": "3.5. Cuando la rescisión de este EULA sea solicitada por el USUARIO, se le concederá un período de hasta 7 (siete) días para los procedimientos de terminación;",
    "terms_duration_6": "3.6. La rescisión de este EULA estará condicionada a la liquidación de todos los montos adeudados hasta la fecha de rescisión;",
    "terms_duration_7": "3.7. Durante el período de aviso para la cancelación del contrato, el USUARIO puede hacer copias de seguridad de los informes en formato PDF, el SOFTWARE proporciona una función para que el USUARIO pueda descargar múltiples informes por proyecto, accediendo a través de la versión WEB. Después de este período, los datos pueden ser eliminados permanentemente.",
    "terms_payment_title": "4. REMUNERACIÓN",
    "terms_payment_1": "4.1. El USUARIO pagará por adelantado al LICENCIANTE los montos especificados en el plan elegido en el momento de la contratación;",
    "terms_payment_2": "4.2. Si el USUARIO, durante la vigencia de este instrumento, desea cambiar de plan, deberá pagar los montos de acuerdo con el nuevo plan y, si hay una tarifa de suscripción, pagar la diferencia entre la suscripción previamente pagada y la suscripción para el nuevo plan, en hasta dos cuotas iguales y consecutivas;",
    "terms_payment_3": "4.3. La tarifa de suscripción no será reembolsada si el cambio es a un plan de menor valor;",
    "terms_payment_4": "4.4. Si el USUARIO, durante la vigencia de este instrumento, desea cancelar su suscripción, ningún monto ya pagado será reembolsado o devuelto. El acceso al SOFTWARE se mantendrá hasta el final del período contratado, y la suscripción no se renovará en el próximo ciclo de facturación (mensual o anual).",
    "terms_payment_5": "4.5. LAS PARTES pueden cambiar automáticamente el plan inicialmente elegido a un plan superior si se alcanzan los límites previamente estipulados;",
    "terms_payment_6": "4.6. Los pagos realizados después de la fecha de vencimiento tendrán el monto principal más corrección monetaria, intereses de mora del 1% (uno por ciento) al mes, una multa del 2% (dos por ciento), honorarios de abogados y costos judiciales, si hay necesidad de intervención de abogado para el cobro de la deuda, todo sin perjuicio de las medidas contractuales y legales aplicables;",
    "terms_payment_7": "4.7. La falta de pago en la fecha determinada para su vencimiento resultará en la suspensión del acceso al SOFTWARE hasta que se regularice la pendencia financiera;",
    "terms_payment_8": "4.8. Si la suspensión, cancelación o finalización de la prueba permanece por un período superior a 90 (noventa) días, el USUARIO acepta que el LICENCIANTE puede eliminar completamente la información ingresada en el SOFTWARE por el USUARIO.",
    "terms_user_obligations_title": "5. OBLIGACIONES DEL USUARIO",
    "terms_user_obligations_intro": "El USUARIO está obligado a:",
    "terms_user_obligations_1": "5.1. Mantener, a su costa, acceso a Internet de banda ancha para utilizar el SOFTWARE;",
    "terms_user_obligations_2": "5.2. Acceder al SOFTWARE a través del navegador recomendado por el LICENCIANTE y mantenerlo siempre actualizado a la última versión del fabricante;",
    "terms_user_obligations_3": "5.3. Comunicarse oficialmente con el LICENCIANTE a través del correo electrónico support@monitoriesuasobras.net;",
    "terms_user_obligations_4": "5.4. Mantener, a su costa, una dirección de correo electrónico válida y frecuentemente leída en los registros del LICENCIANTE para que puedan comunicarse oficialmente;",
    "terms_user_obligations_5": "5.5. Pagar las tarifas de licencia en la forma y plazos estipulados para el plan contratado;",
    "terms_duration_title": "3. TERM AND TERMINATION",
    "terms_duration_1": "3.1. This EULA becomes effective on the date of its acceptance by the USER;",
    "terms_duration_2": "3.2. The licensing term will be valid for an indefinite period, but may be terminated at any time by either party, provided that it is reported with 7 (seven) days notice;",
    "terms_duration_3": "3.3. The termination will not incur any costs for either party;",
    "terms_duration_4": "3.4. In case of termination by the USER, the request must be made through the LICENSOR's official email, as per item 5.3, requesting the service cancellation;",
    "terms_duration_5": "3.5. When the termination of this EULA is requested by the USER, the USER will be granted a period of up to 7 (seven) days for termination procedures;",
    "terms_duration_6": "3.6. The termination of this EULA will be conditioned to the settlement of all amounts due until the termination date;",
    "terms_duration_7": "3.7. During the notice period for contract cancellation, the USER may backup reports in PDF format, the SOFTWARE provides a feature for the USER to download multiple reports per project, accessing through the WEB version. After this period, the data may be permanently deleted.",
    "terms_payment_title": "4. REMUNERATION",
    "terms_payment_1": "4.1. The USER will pay in advance to the LICENSOR the amounts specified in the plan chosen at the time of contracting;",
    "terms_payment_2": "4.2. If the USER, during the term of this instrument, wishes to change plans, they must pay the amounts according to the new plan and, if there is a subscription fee, pay the difference between the previously paid subscription and the subscription for the new plan, in up to two equal and consecutive installments;",
    "terms_payment_3": "4.3. The subscription fee will not be refunded if the change is to a lower-value plan;",
    "terms_payment_4": "4.4. If the USER, during the term of this instrument, wishes to cancel their subscription, no amount already paid will be refunded or returned. Access to the SOFTWARE will be maintained until the end of the contracted period, and the subscription will not be renewed in the next billing cycle (monthly or annual).",
    "terms_payment_5": "4.5. THE PARTIES may automatically change the initially chosen plan to a higher plan if the previously stipulated limits are reached;",
    "terms_payment_6": "4.6. Payments made after the due date will have the principal amount plus monetary correction, late payment interest of 1% (one percent) per month, a fine of 2% (two percent), attorney's fees and court costs, if there is a need for attorney intervention for debt collection, all without prejudice to applicable contractual and legal measures;",
    "terms_payment_7": "4.7. Failure to pay on the determined due date will result in suspension of access to the SOFTWARE until the financial pending is regularized;",
    "terms_payment_8": "4.8. If the suspension, cancellation, or end of the trial remains for a period longer than 90 (ninety) days, the USER agrees that the LICENSOR may completely delete the information entered in the SOFTWARE by the USER.",
    "terms_user_obligations_title": "5. USER OBLIGATIONS",
    "terms_user_obligations_intro": "The USER is obligated to:",
    "terms_user_obligations_1": "5.1. Maintain, at their expense, broadband Internet access to use the SOFTWARE;",
    "terms_user_obligations_2": "5.2. Access the SOFTWARE via browser recommended by the LICENSOR and keep it always updated to the manufacturer's latest version;",
    "terms_user_obligations_3": "5.3. Communicate officially with the LICENSOR through the email support@monitoriesuasobras.net;",
    "terms_user_obligations_4": "5.4. Maintain, at their expense, a valid and frequently read email address in the LICENSOR's records so that they can communicate officially;",
    "terms_user_obligations_5": "5.5. Pay the license fees in the form and deadlines stipulated for the contracted plan;",
    "social_facebook": "Síguenos en Facebook",
    "social_instagram": "Síguenos en Instagram",
    "social_twitter": "Síguenos en Twitter",
    "social_linkedin": "Síguenos en LinkedIn",
    "social_facebook": "Follow us on Facebook",
    "social_instagram": "Follow us on Instagram",
    "social_twitter": "Follow us on Twitter",
    "social_linkedin": "Follow us on LinkedIn"
  }
};

const languageNames: Record<Language, string> = {
  "pt-BR": "Português",
  "en-US": "English",
  "es-ES": "Español"
};

const LanguageContext = createContext<LanguageContextType>({
  language: "pt-BR",
  setLanguage: () => {},
  translations: translations["pt-BR"]
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    return savedLanguage || "pt-BR";
  });

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage) {
      setLanguageState(savedLanguage);
    }
  }, []);

  return (
    <LanguageContext.Provider 
      value={{ 
        language, 
        setLanguage, 
        translations: translations[language] 
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export { languageNames };
